### ISSUE TITLE
Fails to run ng server

### ISSUE THREAD

**Issue by SidharthRaveendran** [nloyola/bbweb-ng#1]
I get this error when using `npm run start`

`ERROR in src/app/root-store/study/study.reducer.ts(20,14): error TS2322: Type 'EntityState<Study> & { lastAddedId: any; lastSearch: any; error: any; searchActive: boolean; searchReplies: {}; studyCounts: {}; enableAllowedIds: any[]; }' is not assignable to type 'State'.
  Types of property 'studyCounts' are incompatible.
    Type '{}' is not assignable to type 'StudyCounts'.
      Property 'total' is missing in type '{}'.`

**Comment by nloyola** [comment]
Fixed in commit 0623053.
